sudo: required
services:
  -docker

before_install:
  - docker build -t connectwithshrey/docker-react-starter -f Dockerfile.dev .

script:
  - docker run -d -p 127.0.0.1:80:4567 connectwithshrey/docker-reeact-starter npm run test -- --coverage
